version: '2'

services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        restart: always
        ports:
            - "2181:2181"
        volumes:
            - ./zk/data:/data
            - ./zk/datalog:/datalog

    kafka:
        image: wurstmeister/kafka:2.13-2.7.0
        ports:
            - "29092:29092"  
            - "9092:9092"
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://:9092
            - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://<externally-accessible-hostname>:<externally-accessible-port>
            - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - ALLOW_PLAINTEXT_LISTENERS=yes
        depends_on:
            - zookeeper
        volumes:
            - ./kafka/data:/var/lib/kafka/data
 
    packagetracker:
        image: de4a/dev-tracker:0.0.2
        ports:
            - "8081:8080"
        depends_on:
            - kafka

    rest-kafka:
        image: confluentinc/cp-kafka-rest:6.1.1
        ports:
            - "8085:8082"
        hostname: rest-kafka
        container_name: rest-kafka
        environment:
            KAFKA_REST_HOST_NAME=rest-kafka
            KAFKA_REST_LISTENERS=http://0.0.0.0:8082
            KAFKA_REST_BOOTSTRAP_SERVERS=kafka:29092
            KAFKA_REST_SASL_MECHANISM=PLAIN
            KAFKA_REST_CLIENT_BOOTSTRAP_SERVERS=kafka:29092
            KAFKA_REST_CLIENT_SASL_MECHANISM=PLAIN
